"""add_printers_refactor_printing_3d

Revision ID: 113dc8f00282
Revises: b7e4529d1465
Create Date: 2026-05-22 06:02:47.192084

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '113dc8f00282'
down_revision: Union[str, None] = 'b7e4529d1465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printers',
    sa.Column('id_printer', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('id_laboratorio', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_laboratorio'], ['laboratories.id_laboratorio'], ),
    sa.PrimaryKeyConstraint('id_printer'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('ix_printers_laboratorio', 'printers', ['id_laboratorio'], unique=False)
    op.add_column('printings_3d', sa.Column('id_printer', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'printings_3d', 'printers', ['id_printer'], ['id_printer'])
    op.drop_column('printings_3d', 'codigo_impresora')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printings_3d', sa.Column('codigo_impresora', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'printings_3d', type_='foreignkey')
    op.drop_column('printings_3d', 'id_printer')
    op.drop_index('ix_printers_laboratorio', table_name='printers')
    op.drop_table('printers')
    # ### end Alembic commands ###
