"""decouple_printing3d_from_loans

Revision ID: 299a89336317
Revises: 113dc8f00282
Create Date: 2026-05-22 06:12:15.372454

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '299a89336317'
down_revision: Union[str, None] = '113dc8f00282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printings_3d', sa.Column('id_usuario', sa.BigInteger(), nullable=False))
    op.add_column('printings_3d', sa.Column('estado', sa.Text(), nullable=True))
    op.add_column('printings_3d', sa.Column('fecha_solicitud', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_constraint(op.f('printings_3d_id_loan_key'), 'printings_3d', type_='unique')
    op.create_index('ix_printings_usuario', 'printings_3d', ['id_usuario'], unique=False)
    op.drop_constraint(op.f('printings_3d_id_loan_fkey'), 'printings_3d', type_='foreignkey')
    op.create_foreign_key(None, 'printings_3d', 'users', ['id_usuario'], ['carnet'])
    op.drop_column('printings_3d', 'id_loan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printings_3d', sa.Column('id_loan', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'printings_3d', type_='foreignkey')
    op.create_foreign_key(op.f('printings_3d_id_loan_fkey'), 'printings_3d', 'loans', ['id_loan'], ['id_loan'])
    op.drop_index('ix_printings_usuario', table_name='printings_3d')
    op.create_unique_constraint(op.f('printings_3d_id_loan_key'), 'printings_3d', ['id_loan'], postgresql_nulls_not_distinct=False)
    op.drop_column('printings_3d', 'fecha_solicitud')
    op.drop_column('printings_3d', 'estado')
    op.drop_column('printings_3d', 'id_usuario')
    # ### end Alembic commands ###
