"""add_imagen_to_resources

Revision ID: 6fd42f900660
Revises: 299a89336317
Create Date: 2026-05-22 07:27:14.169480

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6fd42f900660'
down_revision: Union[str, None] = '299a89336317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('imagen', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'imagen')
    # ### end Alembic commands ###
