"""init

Revision ID: b7e4529d1465
Revises: 
Create Date: 2026-05-21 20:40:21.111764

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b7e4529d1465'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratories',
    sa.Column('id_laboratorio', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_laboratorio'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('materials_3d',
    sa.Column('id_material', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_material', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('users',
    sa.Column('carnet', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('correo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('penalizaciones', sa.Integer(), nullable=True),
    sa.Column('generacion', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('carnet'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('loans',
    sa.Column('id_loan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('codigo_devolucion', sa.Text(), nullable=False),
    sa.Column('responsabilidad', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('fecha_prestamo', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fecha_limite', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.carnet'], ),
    sa.PrimaryKeyConstraint('id_loan'),
    sa.UniqueConstraint('codigo_devolucion')
    )
    op.create_index('ix_loans_estado', 'loans', ['estado'], unique=False)
    op.create_index('ix_loans_usuario', 'loans', ['id_usuario'], unique=False)
    op.create_table('resources',
    sa.Column('id_recurso', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=True),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('id_laboratorio', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_laboratorio'], ['laboratories.id_laboratorio'], ),
    sa.PrimaryKeyConstraint('id_recurso'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('ix_resources_estado', 'resources', ['estado'], unique=False)
    op.create_index('ix_resources_laboratorio', 'resources', ['id_laboratorio'], unique=False)
    op.create_table('loan_details',
    sa.Column('id_detalle', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_loan', sa.BigInteger(), nullable=False),
    sa.Column('id_recurso', sa.BigInteger(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_loan'], ['loans.id_loan'], ),
    sa.ForeignKeyConstraint(['id_recurso'], ['resources.id_recurso'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('printings_3d',
    sa.Column('id_impresion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_loan', sa.BigInteger(), nullable=False),
    sa.Column('id_material', sa.BigInteger(), nullable=False),
    sa.Column('codigo_impresora', sa.Text(), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado', sa.Integer(), nullable=True),
    sa.Column('tipo_trabajo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_loan'], ['loans.id_loan'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materials_3d.id_material'], ),
    sa.PrimaryKeyConstraint('id_impresion'),
    sa.UniqueConstraint('id_loan')
    )
    op.create_table('returns',
    sa.Column('id_devolucion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_loan', sa.BigInteger(), nullable=False),
    sa.Column('fecha_devolucion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('hay_danios', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_loan'], ['loans.id_loan'], ),
    sa.PrimaryKeyConstraint('id_devolucion'),
    sa.UniqueConstraint('id_loan')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('returns')
    op.drop_table('printings_3d')
    op.drop_table('loan_details')
    op.drop_index('ix_resources_laboratorio', table_name='resources')
    op.drop_index('ix_resources_estado', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_loans_usuario', table_name='loans')
    op.drop_index('ix_loans_estado', table_name='loans')
    op.drop_table('loans')
    op.drop_table('users')
    op.drop_table('materials_3d')
    op.drop_table('laboratories')
    # ### end Alembic commands ###
